version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq-dev-test'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-dev-test-net
networks:
  rabbit-dev-test-net:
    name: rabbit-dev-test-net
